version: '3.1'

services:

  server:
    build:
      context: .
      dockerfile: /dockerfile
    ports:
      - 3000:3000

  db:
    container_name: sqlDB
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
